version: '2'

volumes:

  vendor:
    driver: local

  cache:
    external: true

services:

  test:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    entrypoint: ["test.sh"]
    command: ["test-run.sh"]
    volumes:
      - cache:/go/src/phrasebook-api/.glide/
      - vendor:/vendor
    links:
      - db
    environment:
      TEST_NAMESPACE: phrasebook-api/src/...
      TEST_REPORT_PATH: /reports/unit.xml
      DATABASE_DSN: mysql://dev:dev@tcp(db:3306)/dev

  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    entrypoint: ["build.sh"]
    command: ["go", "install"]
    volumes:
      - vendor:/vendor

  agent:
    image: phrasebooklearner/ansible
    links:
      - db
    environment:
      PROBE_HOST: db
      PROBE_PORT: 3306

  migrate:
    build:
      context: ../../
      dockerfile: docker/migrate/Dockerfile
    links:
      - db
    environment:
      MIGRATION_DATABASE: mysql://dev:dev@tcp(db:3306)/dev

  db:
    image: mysql:5.7
    hostname: db
    expose:
      - "3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev