version: '2'

services:

  mysql-agent:
    build:
      context: .
      dockerfile: ansible-playbook/Dockerfile
    working_dir: /ansible
    links:
      - mysql
    volumes:
      - ./ansible-playbook/probe.yml:/ansible/probe.yml
    environment:
      PROBE_HOST: "mysql"
      PROBE_PORT: "3306"
    command: ["probe.yml"]

  mysql:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev

  migrate:
    build:
      context: .
      dockerfile: migrate/Dockerfile
    working_dir: /go/src/app
    volumes:
      - ../migrations:/go/src/app/migrations
    links:
      - mysql
    environment:
      - MIGRATION_DATABASE=mysql://dev:dev@tcp(mysql:3306)/dev